Remove permissions without piping
microsoft/CSS-Exchange pull request #1930
Opened 2024-01-07 17:21 UTC by bill-long

Fixes #1881

Once upon a time, we had to pipe invalid permissions to get them to remove. Testing in my lab on current versions of Exchange indicates this is no longer the case, so I'm removing the pipe. This will allow permissions removal to work in Remote PowerShell.

If we find that piping is still necessary for some scenarios, we may have to revisit this change. This will depend on user feedback.

2024-01-07 18:03 UTC, lusassl-msft approved these changes

2024-01-08 14:07 UTC, dpaulson45 requested changes

2024-01-08 14:07 UTC, dpaulson45 commented on PublicFolders/SourceSideValidations/Tests/Permission/Remove-InvalidPermission.ps1
> +                            Remove-PublicFolderClientPermission $result.FolderEntryId -User $perm.User.DisplayName -Confirm:$false
@bill-long making a change with write, need to have testing team aware of and test out.

2024-01-29 17:07 UTC, dpaulson45 approved these changes
Due to new issues coming up regarding what this fix, we can't wait anymore on the test team. It has been over 3 weeks since this code has been ready for production.

2024-01-29 17:18 UTC, dpaulson45 approved these changes

2024-01-29 17:28 UTC, merged